### PR TITLE
Make it possible to specify languages in configuration phase

### PR DESCRIPTION
**Pull request by fr6nco**
Currently languages are hard coded and we cant edit the list of languages without having to rebuild.
With this change it would be possible to inject the language object at config phase.

### CODE REVIEW

**Comment by giacomo** [comment]
@fr6nco could you please explain me why it is needed?

**Comment by fr6nco** [comment]
I wanted to inject Slovak language, it seems to me, that it is not possible to set a language via config. Perhaps Im missing something? It seems to me that adding a new language requires a new version release.

**Comment by giacomo** [comment]
okay i will check, thanks

**Comment by giacomo** [comment]
Basically adding this custom language this way - it was not intended, you will loose the possibility to use multi language support. I will look at it in near future and add a possibility to add a custom language.

**Comment by fr6nco** [comment]
Not sure it breaks the initial idea, I was able to add 2 languages (EN and SK) with this config:

```
      NgxCookieConsentModule.forRoot({
        availableLanguages: ['en', 'sk'],
        defaultLanguage: 'sk',
        languages: languages as any,
        showLanguageSwitcher: true,
        showFunctionalCookies: false,
        showOtherTools: false,
        showMarketingCookies: false,
        imprintUrl: {
          en: 'https://www.---.com/contact/',
          sk: 'https://www.---.sk/kontakt/',
        },
        privacyPolicyUrl: {
          en: 'https://www.---.sk/gdpr/',
          sk: 'https://www.---.sk/gdpr/',
        },
      })
```

whereas the languages is exported as:
```
export { lang_en } from 'ngx-cookie-consent-tbo';
export { lang_sk } from './sk.language';
```

(I've forked your repo and published to npm, thus 'ngx-cookie-consent-tbo')

Another thing that did not work was the flag, I had to add the css for the slovak flag.

**Pull request closed without merging**
